### ISSUE TITLE
No driver? (i have chromedriver 111)

### ISSUE THREAD

**Issue by yayy80** [plouvart/character-ai-bindings#5]
Exception ignored in: <function ChatRoomServer.__del__ at 0x000001EE246AB130>
Traceback (most recent call last):
  File "C:\Users\bobea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\character_ai_bindings\chatroom.py", line 245, in __del__
    self.driver.quit()
AttributeError: 'ChatRoomServer' object has no attribute 'driver'

**Comment by plouvart** [comment]
Hello.
It's difficult for me to know what exactly is going on without seeing your code, or how it is executed.
Could you add more info about that?

**Comment by yayy80** [comment]
I used the example, i have chrome 111, chrome driver 111, it wont work tho?

**Comment by plouvart** [comment]
You should have had another exception which states that chrome driver version 112 is required, not 111.

**Comment by yayy80** [comment]
Oh! I recently updated Chrome, i think thats why
